# Configuration for Release Drafter: https://github.com/release-drafter/release-drafter
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 💥 Breaking changes
    labels:
      - breaking
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug fixes
    labels:
      - bug
      - bugfix
      - fix
      - regression
  - title: 📝 Documentation
    labels:
      - documentation
  - title: 🚦 Tests
    labels:
      - test
      - tests
  - title: 👻 Maintenance
    labels:
      - chore
      - internal
      - maintenance
  - title: 📦 Dependencies
    labels:
      - dependencies
    collapse-after: 15
  - title: 🗑 Removed
    labels:
      - removed
      - deprecated
  - title: ✍ Other changes

exclude-labels:
  - no-changelog
  - skip-changelog
  - invalid
  - duplicate
  - question
  - wontfix

change-template: '- $TITLE by @$AUTHOR in #$NUMBER'

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

autolabeler:
  - label: documentation
    files:
      - '*.md'
      - '*.rst'
  - label: bug
    branch:
      - /fix\/.+/
      - /bugfix\/.+/
  - label: feature
    branch:
      - /feature\/.+/
      - /feat\/.+/
  - label: chore
    branch:
      - /chore\/.+/
  - label: test
    branch:
      - /test\/.+/
