name: Auto Label

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-label:
    uses: open-delivery-spec/.github/.github/workflows/auto-label.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
